name: Running

on:
  # 수동 실행 트리거 추가
  workflow_dispatch:
  
  schedule:
    # 미국 장 개장 시간 (ET 9:30 AM)
    - cron: '0,30 13 * * 1-5'  # UTC 13:00, 13:30 (미국 서머타임-EDT 9:00, 9:30, 한국 22:00, 22:30)
    - cron: '0,30 14 * * 1-5'  # UTC 14:00, 14:30 (미국 비서머타임-EST 9:00, 9:30, 한국 23:00, 23:30)
    # 30분 간격으로 실행 (서머타임 - 미국 동부 시간 기준)
    - cron: '0,30 15 * * 1-5'  # UTC 15:00, 15:30 (EDT 11:00, 11:30, 한국 00:00, 00:30)
    - cron: '0,30 16 * * 1-5'  # UTC 16:00, 16:30 (EDT 12:00, 12:30, 한국 01:00, 01:30)
    - cron: '0,30 17 * * 1-5'  # UTC 17:00, 17:30 (EDT 13:00, 13:30, 한국 02:00, 02:30)
    - cron: '0,30 18 * * 1-5'  # UTC 18:00, 18:30 (EDT 14:00, 14:30, 한국 03:00, 03:30)
    - cron: '0,30 19 * * 1-5'  # UTC 19:00, 19:30 (EDT 15:00, 15:30, 한국 04:00, 04:30)
    - cron: '0,30 20 * * 1-5'  # UTC 20:00, 20:30 (EDT 16:00, 16:30, 한국 05:00, 05:30)

jobs:
  auto-trading:
    runs-on: ubuntu-latest
    env:
      ID: ${{ secrets.ACCOUNT_ID }}
      ACCOUNT: ${{ secrets.ACCOUNT_NUMBER }}
      APP_KEY: ${{ secrets.ACTUAL_APP_KEY }}
      APP_SECRET: ${{ secrets.ACTUAL_APP_SECRET }}
      VIRTUAL_APP_KEY: ${{ secrets.VIRTUAL_APP_KEY }}
      VIRTUAL_APP_SECRET: ${{ secrets.VIRTUAL_APP_SECRET }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update config.yaml
      run: |
        yq -i '.api_info.id = strenv(ID)' data/config.yaml
        yq -i '.api_info.account = strenv(ACCOUNT)' data/config.yaml
        yq -i '.api_info.app_key = strenv(APP_KEY)' data/config.yaml
        yq -i '.api_info.app_secret = strenv(APP_SECRET)' data/config.yaml
        yq -i '.api_info.virtual_app_key = strenv(VIRTUAL_APP_KEY)' data/config.yaml
        yq -i '.api_info.virtual_app_secret = strenv(VIRTUAL_APP_SECRET)' data/config.yaml
        
    - name: Run ASTP
      run: |
        python main/main.py
      env:
        TZ: Asia/Seoul  # 한국 시간대 설정 