name: ASTP Trading Bot

on:
  schedule:
    # 한국 시간 23:20에 실행 (장 시작 10분 전)
    - cron: '20 14 * * 1-5'  # UTC 기준 14:20 (월-금)

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Check US Market Hours
        id: market-check
        run: |
          # 현재 시간이 미국 공휴일인지 확인하는 로직 추가 가능
          current_hour=$(TZ="America/New_York" date +%H)
          current_day=$(date +%u)
          
          # 주말(6,7) 또는 미국 시장 운영 시간이 아닐 경우 워크플로우 중단
          if [ "$current_day" -ge 6 ] || [ "$current_hour" -lt 9 ] || [ "$current_hour" -ge 16 ]; then
            echo "US market is closed. Skipping execution."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create config file
        run: |
          cat > data/config.yaml << EOF
          api_info:
            id: "${{ secrets.KIS_ID }}"
            account: "${{ secrets.KIS_ACCOUNT }}"
            app_key: "${{ secrets.KIS_APP_KEY }}"
            app_secret: "${{ secrets.KIS_APP_SECRET }}"
            virtual_app_key: "${{ secrets.KIS_VIRTUAL_APP_KEY }}"
            virtual_app_secret: "${{ secrets.KIS_VIRTUAL_APP_SECRET }}"
            is_virtual: true
          
          companies_settings:
            auto_fetch: true
            manual_tickers: []
          
          system:
            operating_cycle: 3600
          
          macd_settings:
            period: "60d"
            interval: "1h"
            ema_short: 12
            ema_long: 26
            signal_period: 9
          
          trading_settings:
            auto_trading_enabled: true
            stop_loss_threshold: -7.0
            take_profit_threshold: 20.0
            max_holding_days: 30
            max_buy_stocks: 3
            budget_percentage: 30
            risk_level: 2
            virtual_balance: 100000000
          EOF

      - name: Run Python Script
        run: python main/main.py