name: Running

on:
  # 수동 실행 트리거 추가
  workflow_dispatch:
  
  schedule:
    # 미국 장 개장 시간 (ET 9:30 AM)
    - cron: '30 13 * * 1-5'  # UTC 13:30 (미국 서머타임-EDT 9:30, 한국 22:30)
    - cron: '30 14 * * 1-5'  # UTC 14:30 (미국 비서머타임-EST 9:30, 한국 23:30)
    # 1시간 간격으로 실행 (서머타임 - 미국 동부 시간 기준)
    - cron: '30 15 * * 1-5'  # UTC 15:30 (EDT 11:30, 한국 00:30)
    - cron: '30 16 * * 1-5'  # UTC 16:30 (EDT 12:30, 한국 01:30)
    - cron: '30 17 * * 1-5'  # UTC 17:30 (EDT 13:30, 한국 02:30)
    - cron: '30 18 * * 1-5'  # UTC 18:30 (EDT 14:30, 한국 03:30)
    - cron: '30 19 * * 1-5'  # UTC 19:30 (EDT 15:30, 한국 04:30)
    - cron: '30 20 * * 1-5'  # UTC 20:30 (EDT 16:30, 한국 05:30)

jobs:
  auto-trading:
    runs-on: ubuntu-latest
    env:
      ID: ${{ secrets.ACCOUNT_ID }}
      ACCOUNT: ${{ secrets.ACCOUNT_NUMBER }}
      APP_KEY: ${{ secrets.ACTUAL_APP_KEY }}
      APP_SECRET: ${{ secrets.ACTUAL_APP_SECRET }}
      VIRTUAL_APP_KEY: ${{ secrets.VIRTUAL_APP_KEY }}
      VIRTUAL_APP_SECRET: ${{ secrets.VIRTUAL_APP_SECRET }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update config.yaml
      run: |
        yq -i '.id = env(ID)' data/config.yaml
        yq -i '.account = env(ACCOUNT)' data/config.yaml
        yq -i '.app_key = env(APP_KEY)' data/config.yaml
        yq -i '.app_secret = env(APP_SECRET)' data/config.yaml
        yq -i '.virtual_app_key = env(VIRTUAL_APP_KEY)' data/config.yaml
        yq -i '.virtual_app_secret = env(VIRTUAL_APP_SECRET)' data/config.yaml
        
    - name: Run ASTP
      run: |
        python main/main.py
      env:
        TZ: Asia/Seoul  # 한국 시간대 설정 