name: ASTP Trading Bot

on:
  schedule:
    # 한국 시간 23:20에 실행 (장 시작 10분 전)
    - cron: '20 14 * * 1-5'  # UTC 기준 14:20 (월-금)

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Check US Market Hours
        id: market-check
        run: |
          # 현재 시간이 미국 공휴일인지 확인하는 로직 추가 가능
          current_hour=$(TZ="America/New_York" date +%H)
          current_day=$(date +%u)
          
          # 주말(6,7) 또는 미국 시장 운영 시간이 아닐 경우 워크플로우 중단
          if [ "$current_day" -ge 6 ] || [ "$current_hour" -lt 9 ] || [ "$current_hour" -ge 16 ]; then
            echo "US market is closed. Skipping execution."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies"
      - name: Run Python Script
        run: python main/main.py