name: Run Python Every Hour
on:
  schedule:
    - cron: "0 * * * *"  # 매 정각마다 실행 (UTC 기준)
  workflow_dispatch:     # 수동 실행 트리거 추가
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies"
      - name: Run Python Script
        run: python main/main.py